export const profile = {
  name: "Rudraksh Mittal",
  firstName: "Rudraksh",
  lastName: "Mittal",
  initials: "RM",
  eyebrow: ["Computer Science", "Artificial Intelligence", "Data Systems", "Real World Problems"],
  heroStatement: "I build AI systems and full-stack products that turn messy data into something real.",
  location: "Bengaluru, India",
  email: "rudrakshmittal19@gmail.com",
  phone: "+91 8285692725",
  linkedin: "https://linkedin.com/in/rudraksh-mittal19",
  github: "https://github.com/rudrakshmittal19-star",
  resumeUrl: "/resume.pdf",
};

export const about = {
  statement: "A curious builder at the intersection of AI, software, and real world problems.",
  body: "I'm a final-year Computer Science (AI & ML) student at CHRIST, Bengaluru. I build systems that turn messy, real-world data, PDFs, settlement records, patient symptoms, into something structured enough to actually act on.",
  facts: [
    { label: "Studying", value: "B.Tech CSE (AI/ML)" },
    { label: "Graduating", value: "2027" },
    { label: "Based in", value: "Bengaluru, India" },
  ],
};

export const projects = [
  {
    id: "01",
    slug: "settlement-recon-agent",
    color: "#5C7A96",
    name: "Settlement Reconciliation Agent",
    short: "Reconciles Razorpay settlements against merchant ledgers, with an LLM reasoning layer for the ambiguous cases.",
    tags: ["AI", "Automation", "Fintech"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/settlement-recon-agent",
    liveDemo: "https://settlement-recon-agent.vercel.app/",
  },
  {
    id: "02",
    slug: "promptforge",
    color: "#7A6C9E",
    name: "PromptForge",
    short: "A five-agent pipeline that rewrites and scores prompts side by side, streamed live.",
    tags: ["LLM", "Multi-agent", "SSE"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/PromptForge",
    liveDemo: "https://promptforge-chat.vercel.app/",
  },
  {
    id: "03",
    slug: "mediassist",
    color: "#5C9490",
    name: "MediAssist",
    short: "An AI healthcare chatbot for symptom analysis, report uploads, and conversational assistance.",
    tags: ["Healthcare", "Full Stack"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/EonmedChatbot",
    liveDemo: "https://eonmed-chatbot.vercel.app/",
  },
  {
    id: "04",
    slug: "incidentai",
    color: "#B8834A",
    name: "IncidentAI",
    short: "AI-powered incident management workflows for ServiceNow, built during my HCLTech internship.",
    tags: ["Enterprise", "ServiceNow"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/incidentai",
    liveDemo: "https://incidentai.vercel.app/",
  },
  {
    id: "05",
    slug: "recoverai",
    color: "#A9634F",
    name: "recoverai",
    short: "Scores failed payments on recovery probability, so retries go where they're actually worth it.",
    tags: ["Python", "XGBoost", "scikit-learn"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/recoverai",
    liveDemo: null,
  },
  {
    id: "06",
    slug: "knowledge-nexus",
    color: "#6E8B63",
    name: "Knowledge Nexus",
    short: "A full-stack ERP for a coaching institute, covering records, attendance, fees, and scheduling.",
    tags: ["Next.js", "Supabase", "Groq AI"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star",
    liveDemo: null,
  },
  {
    id: "07",
    slug: "preppilot-ai",
    color: "#5A8A99",
    name: "PrepPilot AI",
    short: "AI-evaluated viva and interview prep, with adaptive practice across text, speech, and MCQs.",
    tags: ["AI Evaluation", "Adaptive Practice"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/prep-pilot-ai",
    liveDemo: null,
  },
  {
    id: "08",
    slug: "ai-resume-matcher",
    color: "#A6924A",
    name: "AI Resume-Job Matcher",
    short: "NLP-based resume screening that ranks candidates against a job description.",
    tags: ["Python", "NLP"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/AI-Resume-Assistant",
    liveDemo: null,
  },
  {
    id: "09",
    slug: "gearguard",
    color: "#6B7280",
    name: "GearGuard",
    short: "A maintenance-tracking platform for equipment and technicians.",
    tags: ["TypeScript", "MongoDB", "Auth"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/gearguard-maintenance-system",
    liveDemo: null,
  },
  {
    id: "10",
    slug: "ckpl-auction-hub",
    color: "#8C5464",
    name: "CKPL Auction Hub",
    short: "A sports auction platform for team and player bidding and allocations.",
    tags: ["React", "TypeScript", "shadcn/ui"],
    year: "2026",
    github: "https://github.com/rudrakshmittal19-star/ckpl-auction-platform",
    liveDemo: null,
  },
  {
    id: "11",
    slug: "ai-smart-event-management",
    color: "#B39558",
    name: "AI Smart Event Management",
    short: "An event scheduling and registration platform with AI-assisted audience insights, built as a SAP Labs Vibethon finalist entry.",
    tags: ["TypeScript", "Event Management"],
    year: "2025",
    github: "https://github.com/rudrakshmittal19-star/Event-Management-Site",
    liveDemo: null,
  },
  {
    id: "12",
    slug: "sustainable-guest-management",
    color: "#5E7A5A",
    name: "Sustainable Guest Management System",
    short: "Tracks guest water and energy use against benchmarks and automates eco-certificates, built for Jungle Lodges & Resorts.",
    tags: ["Python", "Automation"],
    year: "2025",
    github: "https://github.com/rudrakshmittal19-star",
    liveDemo: null,
  },
];

export const experience = [
  {
    id: "01",
    slug: "hcltech",
    org: "HCLTech",
    logo: "/logos/hcltech.png",
    location: "Noida, India",
    title: "AI Intern",
    dates: "Apr 2026 – Jun 2026",
    status: "Shipped",
    summary:
      "Built AI-powered incident management workflows for ServiceNow IncidentAI, using prompt engineering and structured incident datasets to automate issue reporting, and designed reusable prompt templates that improved information retrieval speed for enterprise IT support.",
    points: [
      "Built AI-powered incident management workflows for ServiceNow IncidentAI, using prompt engineering and structured incident datasets to automate issue reporting for enterprise IT support.",
      "Designed incident data models and reusable prompt templates that improved information retrieval speed and reporting accuracy for enterprise support teams.",
    ],
    tags: ["Prompt Engineering", "ServiceNow", "Enterprise IT"],
  },
  {
    id: "02",
    slug: "eonmed",
    org: "EONMED",
    logo: "/logos/eonmed.png",
    location: "Remote",
    title: "AI Intern",
    dates: "Apr 2026 – May 2026",
    status: "Deployed",
    summary:
      "Developed MediAssist, an AI-powered healthcare chatbot for symptom analysis, medical report uploads, and conversational assistance using the Gemini API, with a Supabase backend deployed on Vercel for secure authentication and real-time report management.",
    points: [
      "Developed MediAssist, an AI-powered healthcare chatbot supporting symptom analysis, medical report uploads, and conversational assistance using the Gemini API.",
      "Integrated a Supabase backend and deployed the application on Vercel, enabling secure authentication and real-time medical report management.",
    ],
    tags: ["Gemini API", "Supabase", "Vercel", "Healthcare"],
  },
  {
    id: "03",
    slug: "droom",
    org: "Droom Technology",
    logo: "/logos/droom.png",
    location: "Gurugram, India",
    title: "Engineering Intern",
    dates: "Apr 2025 – May 2025",
    status: "Published",
    summary:
      "Built a Python ETL pipeline using PyMuPDF, Camelot, and pdfplumber to extract structured data from 1,000+ vehicle inspection PDFs, and published the resulting ML-ready datasets on Hugging Face.",
    points: [
      "Built a Python ETL pipeline using PyMuPDF, Camelot, and pdfplumber to extract structured data from 1,000+ vehicle inspection PDFs.",
      "Published the resulting ML-ready datasets on Hugging Face to support downstream analytics for the engineering team.",
    ],
    tags: ["ETL", "PyMuPDF", "Camelot", "Hugging Face"],
  },
  {
    id: "04",
    slug: "metvy",
    org: "Metvy",
    logo: "/logos/metvy.jpeg",
    location: "Remote",
    title: "Marketing & Sales Intern",
    dates: "Feb 2025 – Apr 2025",
    status: "Completed",
    summary:
      "Generated qualified leads and supported outreach initiatives to drive client acquisition, while analyzing campaign performance metrics and conducting market research to improve conversion strategies.",
    points: [
      "Generated qualified leads and supported outreach initiatives to drive client acquisition.",
      "Analyzed campaign performance metrics and conducted market research to improve conversion strategies.",
    ],
    tags: ["Lead Generation", "Market Research", "Campaign Analysis"],
  },
];

export const skillStreams = {
  row1: ["PYTHON", "SQL", "NLP", "PROMPT ENGINEERING", "LLM APPLICATIONS", "PANDAS", "SCIKIT-LEARN", "HUGGING FACE", "GEMINI API"],
  row2: ["JAVA", "C", "GIT", "GITHUB", "SUPABASE", "VERCEL", "NEXT.JS", "TYPESCRIPT", "MYSQL", "MONGODB"],
};

export const timeline = [
  {
    year: "2026",
    title: "HCLTech",
    subtitle: "AI Intern",
    detail: "Built AI-powered incident management workflows for ServiceNow IncidentAI.",
    type: "experience",
  },
  {
    year: "2026",
    title: "EONMED",
    subtitle: "AI Intern",
    detail: "Developed MediAssist, an AI-powered healthcare chatbot.",
    type: "experience",
  },
  {
    year: "2025",
    title: "Droom Technology",
    subtitle: "Engineering Intern",
    detail: "Built a Python ETL pipeline, published the dataset on Hugging Face.",
    type: "experience",
  },
  {
    year: "2025",
    title: "SAP Labs Vibethon",
    subtitle: "Finalist, College Edition",
    detail: "Reached the finals with an AI-assisted event platform.",
    type: "achievement",
  },
];

export const education = {
  university: "CHRIST (Deemed to be University), Bengaluru",
  degree: "B.Tech Computer Science Engineering, AI & ML",
  dates: "Jul 2023 – May 2027 (Expected)",
};

export const certifications = [
  { year: "2025", name: "MongoDB Data Modeling Path", org: "MongoDB", detail: "11 December 2025" },
  { year: "2025", name: "Image Processing Onramp", org: "MathWorks Training Services", detail: "Completed 100% · 4 December 2025" },
  { year: "2025", name: "MongoDB Python Developer Path", org: "MongoDB", detail: "22 July 2025" },
  { year: "2025", name: "MongoDB Basics", org: "MongoDB University", detail: "Jul 2025" },
  { year: "2025", name: "IBM Cognos Analytics", org: "IBM Cognitive Class", detail: "Jul 2025" },
  { year: "2025", name: "Operating Systems Foundations", org: "Scaler Academy", detail: "Jun 2025" },
  { year: "2024", name: "Java Programming", org: "Oracle Academy", detail: "Dec 2024" },
  { year: "2024", name: "Build Your Own Chatbot (Level 1)", org: "IBM", detail: "Oct 2024" },
  { year: "2024", name: "Introduction to Data Science", org: "Cisco Networking Academy", detail: "Sep 2024" },
  { year: "2023", name: "Advanced Excel for Data Analysis", org: "Microsoft", detail: "Jul 2023" },
];

export const achievements = [
  {
    year: "2025",
    title: "Finalist, SAP Labs Vibethon (College Edition)",
    org: "SAP Labs",
    detail: "March 2025",
  },
  {
    year: "2025",
    title: "NASA International Space Apps Challenge",
    org: "Team ExoSky · CHRIST Kengeri Campus",
    detail: "August 2025",
  },
  {
    year: "2025",
    title: "Published ML-Ready Vehicle Inspection Dataset",
    org: "Hugging Face · Droom Technology",
    detail: "May 2025",
  },
  {
    year: "2025",
    title: "1st Position — Basketball",
    org: "AIML&DS Bootcamp · CHRIST",
    detail: "15 December 2025",
  },
  {
    year: "2025",
    title: "1st Position — Foosball",
    org: "AIML&DS Bootcamp · CHRIST",
    detail: "15 December 2025",
  },
  {
    year: "2024",
    title: "1st Position — Basketball",
    org: "Inter-Department Basketball Tournament · CHRIST Kengeri Campus",
    detail: "20 November 2024",
  },
];

export const leadership = [
  {
    year: "2025",
    title: "Crew Member — ANVESHA'25",
    org: "CHRIST (Deemed to be University)",
    detail: "23–24 July 2025",
  },
  {
    year: "2025",
    title: "Sports Media Head & Overall Coordinator, Devadan Cup",
    org: "Dept. of Physical Education, CHRIST University",
    detail: "Jun 2025 – Apr 2026",
  },
  {
    year: "2025",
    title: "Volunteer to Program Coordinator (POC)",
    org: "Centre for Social Action (CSA), CHRIST University",
    detail: "Jun 2025 – Apr 2026",
  },
  {
    year: "2025",
    title: "Volunteer — DAKSH 2025",
    org: "Education & Career Guidance Fair · Student Council, CHRIST",
    detail: "11–12 January 2025",
  },
  {
    year: "2024",
    title: "Participant — Blossoms 2024 (Dumb Charades)",
    org: "CHRIST Kengeri Campus",
    detail: "2024",
  },
  {
    year: "2023",
    title: "Volunteer — Annual Sports Meet",
    org: "CHRIST Kengeri Campus",
    detail: "2023",
  },
];

